spring.application.name: auth-service

auth.jwt:
        refresh.duration: 1048576
        expiration: 1048576
        secret: 6873428E30E5A65D1928D76FF14F5AF69A8AF2024439B65ABE97953D69EC5999
        header: Authorization
        header.prefix: Bearer

spring.jpa.database: postgresql
spring.datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}

logging.level:
        root: info

spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true
