spring.application.name: item-service

kafka:
    topic: orders
    bootstrapServers: ${KAFKA_SERVERS}
    producerClientId: item-producer
    consumerClientId: item-consumer
    consumerGroup: item-group

spring.r2dbc:
  url: ${POSTGRES_URL}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}

logging.level:
  root: debug

spring.liquibase.url: ${POSTGRES_JDBC_URL}
spring.liquibase.user: ${POSTGRES_USERNAME}
spring.liquibase.password: ${POSTGRES_PASSWORD}
